[Engine.GameInfo]
DefaultGame=DustGame.DustTeamGame
DefaultServerGame=DustGame.DustTeamGame_Commander
bAdminCanPause=false
MaxPlayers=16
GameDifficulty=+1.0
bChangeLevels=True
MaxSpectators=2
MaxIdleTime=+0.0
MaxTimeMargin=+0.0
TimeMarginSlack=+1.35
MinTimeMargin=-1.0
TotalNetBandwidth=32000
MaxDynamicBandwidth=7000
MinDynamicBandwidth=4000
DefaultGameType=DustGame.DustTeamGame
DefaultPlayerName=%computername%

[Engine.AccessControl]
IPPolicies=ACCEPT;*

[DefaultPlayer]
Name=DustPlayer
team=255
gametype=gamemode_login

[Engine.HUD]
bMessageBeep=true
HudCanvasScale=0.95
ConsoleMessageCount=4
ConsoleFontSize=5
MessageFontOffset=0
bShowHud=true
DebugDisplay=AI

[Engine.PlayerController]
bAimingHelp=false
InteractDistance=512
bCheckRelevancyThroughPortals=true
MaxConcurrentHearSounds=32
bLogHearSoundOverflow=FALSE
ForceFeedbackManagerClassName=PS3Drv.PS3ForceFeedbackManager

[Engine.Weapon]
Priority=-1.0

[Engine.WorldInfo]
DefaultGravityZ=-980.0
RBPhysicsGravityScaling=1.0
MaxPhysicsSubsteps=5
SquintModeKernelSize=128.0
EmitterPoolClassPath=DustGame.DustEmitterPool
DecalManagerClassPath=Engine.DecalManager
FractureManagerClassPath=
FracturedMeshWeaponDamage=1.0
ChanceOfPhysicsChunkOverride=1.0
bEnableChanceOfPhysicsChunkOverride=FALSE
FractureExplosionVelScale=1.0
DefaultAmbientZoneSettings=(bIsWorldInfo=true)
bPersistPostProcessToNextLevel=TRUE

[Engine.AutoTestManager]
NumMinutesPerMap=50
#CommandsToRunAtEachTravelTheWorldNode=MemLeakCheck
#CommandsToRunAtEachTravelTheWorldNode=SNAPSHOTMEMORY

[Engine.DecalManager]
DecalLifeSpan=10.0

[Engine.MobileHUD]
;MobileInputZones=(InputKey=XboxTypeS_DPad_Left,Desc="Toggle Tilt",X=320,Y=0,SizeX=150,SizeY=30)
;MobileInputZones=(InputKey=XboxTypeS_LeftY,HorizontalInputKey=XboxTypeS_LeftX,Desc="Move",X=30,Y=210,SizeX=100,SizeY=80,bIsAnalogZone=TRUE,VertMultiplier=-1.0,HorizMultiplier=1.0)
;MobileInputZones=(InputKey=XboxTypeS_RightY,HorizontalInputKey=XboxTypeS_RightX,Desc="",X=-1,Y=-1,SizeX=100,SizeY=100,bIsAnalogZone=TRUE,VertMultiplier=1.0,HorizMultiplier=1.0)

[Configuration]

[Engine.GameReplicationInfo]
ServerName=aaa
ShortName=Server
MessageOfTheDay=

[DustGame.DustEmitterPool]
bLogPoolOverflow=1

[DustGame.DustTeamGame]
MaxPlayers=100
EndTimeDelay=4.0
m_OutputFPS=false
m_FPSInterval=1

[DustGame.DustStationGame]
NpeComponent=NPE_GN_NPE01L

[DustGame.DustWorldInfo]
mDefaultSoundSpeed=100000.0
mOverviewMapCameraMinHeight=43690.0
mOverviewMapCameraDefaultHeight=140000.0
mOverviewMapCameraMaxHeight=250000.0

[DustGame.SampleClass]
MyString=Test

[DebugWindows]
RemoteControlX=0
RemoteControlY=0

[DustGame.DustSkelControl_Recoil]
m_bApplyEffect=true

[DustGame.DustPlayerController]
mPauseGame=false
mUseForceFeedBack=true

[DustGame.DustPawn]
mHighZSpeed=-500
mCameraAnimBlendInTime=2
mCameraAnimBlendOutTime=0.5

[Engine.StartupPackages]
Package+=DustGameContent

[DustGame.DustGameSession]
mDefaultGameFlowIndex=2
mDedicatedServerFlowIndex=3
mEditorFlowIndex=4

[DustGameContent.DustPawnContent]
mTakeHitThreshold=10
mLowHealthThreshold=1
mMinBulletWhipInterval=0.2
mMeshTranslationInterpSpeed=(X=10, Y=10, Z=2)
mModifyCollisionWhenCrouching=false

[DustGame.DustGameFlow]
mUseOnlineMode=true

[DustGame.DustGameFlowEos]
mUseOnlineMode=true
mCharacterInfos[0]=(charID=0, charName="local character 0");
mCharacterInfos[1]=(charID=1, charName="local character 1");
mCharacterInfos[2]=(charID=2, charName="local character 2");

[DustGame.DustGameEventManager]
mDumpToExcel=true

[DustGame.StatBudgets]
StatBudgetSetup=(		m_Name="SDK",			m_Budget_Main= 43.0f,	m_Budget_GPU=  7.0f,	m_Budget_Texture=  0.0f		)
StatBudgetSetup=(		m_Name="Executable",		m_Budget_Main= 32.0f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.0f		)
StatBudgetSetup=(		m_Name="CommandBuf",		m_Budget_Main=  2.0f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.0f		)
StatBudgetSetup=(		m_Name="System",		m_Budget_Main=  5.5f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.0f		)
StatBudgetSetup=(		m_Name="MallocOvrhd",		m_Budget_Main=  9.0f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.0f		)
StatBudgetSetup=(		m_Name="Code",			m_Budget_Main=  20.0f,	m_Budget_GPU=  50.0f,	m_Budget_Texture=  2.0f		)
StatBudgetSetup=(		m_Name="Catma",			m_Budget_Main=  5.0f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.0f		)
StatBudgetSetup=(		m_Name="Python",		m_Budget_Main=  12.0f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.f		)
StatBudgetSetup=(		m_Name="Global",		m_Budget_Main=  0.1f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.0f		)
StatBudgetSetup=(		m_Name="Level",			m_Budget_Main=  21.0f,	m_Budget_GPU=  10.0f,	m_Budget_Texture=  57.0f	)
StatBudgetSetup=(		m_Name="Terrain",		m_Budget_Main=  13.0f,	m_Budget_GPU=  0.5f,	m_Budget_Texture=  25.1f, m_GPUTiming = true)
StatBudgetSetup=(		m_Name="Effects",		m_Budget_Main=  3.0f,	m_Budget_GPU=  0.5f,	m_Budget_Texture=  10.0f, m_GPUTiming = true	)
StatBudgetSetup=(		m_Name="Character",		m_Budget_Main=  2.0f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  10.0f, m_GPUTiming = true	)
StatBudgetSetup=(		m_Name="Animation",		m_Budget_Main=  5.5f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.0f, m_GPUTiming = true	)
StatBudgetSetup=(		m_Name="Audio",			m_Budget_Main=  12.5f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.0f		)
StatBudgetSetup=(		m_Name="Vehicle",		m_Budget_Main=  1.5f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  10.0f, m_GPUTiming = true	)
StatBudgetSetup=(		m_Name="Weapons",		m_Budget_Main=  2.5f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  6.0f, m_GPUTiming = true	)
StatBudgetSetup=(		m_Name="UI",			m_Budget_Main=  10.0f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  10.0f		)
StatBudgetSetup=(		m_Name="Installation",		m_Budget_Main=  1.0f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  10.0f, m_GPUTiming = true	)
StatBudgetSetup=(		m_Name="Shaders",		m_Budget_Main=  5.5f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.0f		)
StatBudgetSetup=(		m_Name="Editor",		m_Budget_Main=  0.0f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.0f		)
StatBudgetSetup=(		m_Name="Bink",			m_Budget_Main=  0.0f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.0f		)
StatBudgetSetup=(		m_Name="StarMap",		m_Budget_Main=  0.0f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.0f		)
StatBudgetSetup=(		m_Name="Unknown",		m_Budget_Main=  0.25f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.0f		)
StatBudgetSetup=(		m_Name="STATS",			m_Budget_Main=  0.0f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.0f		)
StatBudgetSetup=(		m_Name="PHYSX",			m_Budget_Main=  10.0f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.0f		)
StatBudgetSetup=(		m_Name="GCM",			m_Budget_Main=  11.11f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.0f		)
StatBudgetSetup=(		m_Name="MeshStreaming",	m_Budget_Main=  9.0f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.0f		)
StatBudgetSetup=(		m_Name="Dynamic",	m_Budget_Main=  4.0f,	m_Budget_GPU=  0.0f,	m_Budget_Texture=  0.0f		)
StatBudgetPrefixes=(	m_Name="Audio",			m_Prefixes=( "A_", "AU_", "AkAudio", "Sound", "XAudio" ) )
StatBudgetPrefixes=(	m_Name="Effects",		m_Prefixes=( "VFX_" ) )
StatBudgetPrefixes=(	m_Name="Character",		m_Prefixes=( "Char_", "CH_", "DR_" ) )
StatBudgetPrefixes=(	m_Name="Animation",		m_Prefixes=( "ANIM_" ) )
StatBudgetPrefixes=(	m_Name="Level",			m_Prefixes=( "OP", "CaptainsQuarters", "BD", "LD", "LM_", "War_Room", "WB_", "HB_", "NC_", "UC_", "MQ_", "LightVolumetrics", "NPE", "MN", "Mega", "MT_", "MTMP", "Terrain_", "Terrian_", "Sky", "Water", "LoginScene", "MOOD_", "SM_", "CS_", "CM_", "CL_" ) )
StatBudgetPrefixes=(	m_Name="Vehicle",		m_Prefixes=( "VH_", "VEH_", "Vehicle" ) )
StatBudgetPrefixes=(	m_Name="Weapons",		m_Prefixes=( "WP_", "WPTU_", "WPGN_", "EQ_", "DRWP_" ) )
StatBudgetPrefixes=(	m_Name="StarMap",		m_Prefixes=( "Space", "StarMap", "UI_Planet" ) )
StatBudgetPrefixes=(	m_Name="UI",			m_Prefixes=( "Deelite", "GfxUI", "UI", "DefaultUI", "Flash_", "Minimap", "CorpIcons") )
StatBudgetPrefixes=(	m_Name="Installation",		m_Prefixes=( "IN_", "WPBA_" ) )
StatBudgetPrefixes=(	m_Name="Global",		m_Prefixes=( "GLO", "Share" ) )
StatBudgetPrefixes=(	m_Name="Code",			m_Prefixes=( "CORE", "ONLINESUB", "ENGINE", "DUST", "TRANSIENT", "PROFILE", "EVENT", "CONTROLLER", "UNREALSCRIPT", "TARGETDATA", "IPDRV", "XE", "GameFramework" ) )
StatBudgetPrefixes=(	m_Name="Shaders",		m_Prefixes=( "LocalShader", "RefShader", "GlobalShader" ) )
StatBudgetPrefixes=(	m_Name="Editor",		m_Prefixes=( "Editor", "UnrealEd" ) )
StatBudgetPrefixes=(	m_Name="Python",		m_Prefixes=( "Py" ) )
StatBudgetPrefixes=(	m_Name="Catma",		m_Prefixes=( "Catma_", "Asset_" ) )
StatBudgetGraphGroups=( m_GraphName="CharsAndVehicles", m_Categories=( "Character", "Vehicle" ) )
StatBudgetGraphGroups=( m_GraphName="UI", m_Categories=( "SDK", "Executable", "System", "Code" ) )

[DustMemDisplay]
DisplayMaxPercent=200
DisplayAreaX=100
DisplayAreaY=200
DisplayAreaWidth=1080
DisplayAreaHeight=50

[DustTimingGraph]
BarTopX=100
BarTopY=10
BarBottomX=100
BarBottomY=600
PPU_PLAYER=0.5
PPU_ANIMATION=8.0
PPU_PAWN=4.0
PPU_WEAPON=2.0
PPU_PARTICLE=1.0
PPU_UI=2.0
PPU_ASYNC=5.0
PPU_NET=2.0
PPU_INPUT=0.5
PPU_SVC=0.1
PPU_MEGATERRAIN_BULK=2.0
PPU_GC=1.0
DisplayLegend=false
DisplayLegendOnlyOverBudget=true
TimeLineDisplayLength=120
DisplayGraphDuringTrace=false

[DustGame.DustSkeletalLODManager]
m_SkeletalLodGroups=(mGroupName="Character", m_LodBudgets=(4, 4, 100), mTickRate=(0, 2, 4), m_LodGroupPrefixes=("Char_", "CH_") )
m_SkeletalLodGroups=(mGroupName="Vehicle", m_LodBudgets=(4, 4, 100), mTickRate=(0, 2, 4), m_LodGroupPrefixes=("VH_") )
m_SkeletalLodGroups=(mGroupName="Weapon", m_LodBudgets=(4, 4, 100), mTickRate=(0, 2, 4), m_LodGroupPrefixes=("WP_") )
m_SkeletalLodGroups=(mGroupName="Installation", m_LodBudgets=(4, 4, 100), mTickRate=(0, 2, 4), m_LodGroupPrefixes=("IN_") )
m_GroupsToIgnoreSkeletalLODManager=_1P_
SkeletalMeshBudgets=(   Name="IgnoreTurretSight", 	Identifier= ("WP_CA_TurretSight_SKM"), 	LodNumLoaded=( 1, 1, 0), LodVerts=( 99999999, 99999999, 99999999), LodTriangles=( 99999999, 99999999, 99999999), LodMemory=(99999999, 99999999, 99999999), TotalMemory=99999999 )
SkeletalMeshBudgets=(  Name="IgnoreSkeletalCube", 	Identifier= ("SkeletalCube"), 		LodNumLoaded=( 1, 1, 0), LodVerts=( 99999999, 99999999, 99999999), LodTriangles=( 99999999, 99999999, 99999999), LodMemory=(99999999, 99999999, 99999999), TotalMemory=99999999 )
SkeletalMeshBudgets=(	Name="Weapons1P",		Identifier= ("WP_1P_"),			LodNumLoaded=( 0, 0, 0), LodVerts=( 3500,    0,    0), LodTriangles=( 5000,    0,    0), LodMemory=(103500,     0,     0), TotalMemory=103500	)
SkeletalMeshBudgets=(	Name="Weapons3P",		Identifier= ("WP_3P_"),			LodNumLoaded=( 4, 8, 0), LodVerts=( 2200, 1500,  600), LodTriangles=( 2000, 1500,  600), LodMemory=( 58200, 40500, 16200), TotalMemory=114900	)
SkeletalMeshBudgets=(	Name="Grenades1P",		Identifier= ("WPGN_1P_"),		LodNumLoaded=( 1, 0, 0), LodVerts=(  500,    0,    0), LodTriangles=(  500,    0,    0), LodMemory=( 13500,     0,     0), TotalMemory= 13500	)
SkeletalMeshBudgets=(	Name="Grenades3P",		Identifier= ("WPGN_3P_"),		LodNumLoaded=( 3, 0, 0), LodVerts=(  100,    0,    0), LodTriangles=(  100,    0,    0), LodMemory=(  2700,     0,     0), TotalMemory=  3500	)
SkeletalMeshBudgets=(	Name="Knife1P",			Identifier= ("WPM_1P_"),		LodNumLoaded=( 1, 0, 0), LodVerts=( 1000,    0,    0), LodTriangles=( 1100,    0,    0), LodMemory=( 27600,     0,     0), TotalMemory= 27600	)
SkeletalMeshBudgets=(	Name="Knife3P",			Identifier= ("WPM_3P_"),		LodNumLoaded=( 1, 0, 0), LodVerts=(  300,    0,    0), LodTriangles=(  300,    0,    0), LodMemory=(  8100,     0,     0), TotalMemory=  8100	)
SkeletalMeshBudgets=(	Name="Characters1P",   		Identifier= ("CH_1P_"),			LodNumLoaded=( 1, 0, 0), LodVerts=( 8000,    0,    0), LodTriangles=( 9000,    0,    0), LodMemory=(222000,     0,     0), TotalMemory=222000	)
SkeletalMeshBudgets=(	Name="Characters3P",   		Identifier= ("CH_3P_"),			LodNumLoaded=( 4, 8, 0), LodVerts=( 8280, 5060,  920), LodTriangles=( 9000, 5500, 1000), LodMemory=(227880,139260, 25320), TotalMemory=392460	)
SkeletalMeshBudgets=(	Name="Drones",   		Identifier= ("DR_"),			LodNumLoaded=( 1, 1, 0), LodVerts=( 8280, 5060,  920), LodTriangles=( 9000, 5500, 1000), LodMemory=(227880,139260, 25320), TotalMemory=392460	)
SkeletalMeshBudgets=(	Name="DroneWeapons",		Identifier= ("DRWP_"),			LodNumLoaded=( 4, 8, 0), LodVerts=( 2200, 1500,  600), LodTriangles=( 2000, 1500,  600), LodMemory=( 58200, 40500, 16200), TotalMemory=114900	)
SkeletalMeshBudgets=(	Name="SmallInstallations",	Identifier= ("IN_S_"),		 	LodNumLoaded=( 1, 1, 0), LodVerts=( 4000, 2000, 1000), LodTriangles=( 2500, 1250,  625), LodMemory=( 99000, 49500, 24750), TotalMemory=173250	)
SkeletalMeshBudgets=(	Name="MediumInstallations",	Identifier= ("IN_M_"),		 	LodNumLoaded=( 2, 2, 0), LodVerts=( 5000, 2500, 1250), LodTriangles=( 3500, 1750,  875), LodMemory=(126000, 63000, 31500), TotalMemory=220500	)
SkeletalMeshBudgets=(	Name="LargeInstallations",  	Identifier= ("IN_L_"),	 		LodNumLoaded=( 3, 5, 0), LodVerts=( 8500, 4250, 2125), LodTriangles=( 5000, 2500, 1250), LodMemory=(208500,104250, 52125), TotalMemory=364857	)
SkeletalMeshBudgets=(  Name="LargeInstallationsExtras",Identifier= ("IN_LX_"), 		LodNumLoaded=( 1, 1, 0), LodVerts=( 1750,  950,  400), LodTriangles=( 1500,  750,  250), LodMemory=( 45750, 24450,  9900), TotalMemory=80100    )
SkeletalMeshBudgets=(	Name="InstallationBarrels",	Identifier= ("WPBA_"),			LodNumLoaded=( 1, 1, 0), LodVerts=( 3000, 1500,  750), LodTriangles=( 2500, 1250,  625), LodMemory=( 78000, 39000, 19500), TotalMemory=136500	)
SkeletalMeshBudgets=(	Name="OldInstallations",	Identifier= ("IN_"),		 	LodNumLoaded=( 1, 1, 0), LodVerts=(10000, 5000, 2000), LodTriangles=( 6000, 3000, 1200), LodMemory=(246000,123000, 49200), TotalMemory=418200	)
SkeletalMeshBudgets=(	Name="Equipment1P",		Identifier= ("EQ_1P_"),			LodNumLoaded=( 5, 0, 0), LodVerts=( 2000,    0,    0), LodTriangles=( 1300,    0,    0), LodMemory=( 49800,     0,     0), TotalMemory=49800	)
SkeletalMeshBudgets=(	Name="Equipment3P",		Identifier= ("EQ_3P_"),			LodNumLoaded=( 4, 5, 0), LodVerts=( 1500,  750,  300), LodTriangles=( 1000,  500,  200), LodMemory=( 37500, 18750,  7500), TotalMemory=63750	)
SkeletalMeshBudgets=(	Name="RDV",			Identifier= ("VH_", "_RDV_"), 		LodNumLoaded=( 1, 1, 0), LodVerts=(12000, 6000, 2400), LodTriangles=( 7000, 3500, 1400), LodMemory=(294000,147000, 58800), TotalMemory=499800	)
SkeletalMeshBudgets=(	Name="MCC",			Identifier= ("VH_", "_MCC_"), 		LodNumLoaded=( 1, 2, 0), LodVerts=( 8000, 4000, 2000), LodTriangles=( 8000, 4000, 2000), LodMemory=(216000,108000, 54000), TotalMemory=378000	)
SkeletalMeshBudgets=(	Name="Vehicles",		Identifier= ("VH_"),			LodNumLoaded=( 2, 6, 0), LodVerts=(12000, 6000, 2400), LodTriangles=( 7000, 3500, 1400), LodMemory=(294000,147000, 58800), TotalMemory=499800	)
SkeletalMeshBudgets=(	Name="VehicleTurrets", 		Identifier= ("WPTU_"),			LodNumLoaded=( 2, 4, 0), LodVerts=( 4000, 2000, 1000), LodTriangles=( 3500, 1750,  875), LodMemory=(105000, 52500, 26250), TotalMemory=183750	)

[UnrealEd.SkeletalBudgetManager]
//When calculating 'Artist Budget'=(NumVerts * VertexBudgetCoeff) + (NumTriangles * TriBudgetCoeff)
VertexBudgetCoeff=40; //When calculating actual numbers in the chart 21kb/vert is used.
TriBudgetCoeff=6;

[DustArtistAllowances]
MaxLightAllowance=10
MaxDirectionalLightAllowance=1
MaxDecalAllowance=10
MaxObjectAllowance=2000
TotalMeshElementAllowance=3000
PerLODMeshElementAllowance=2000
VisibleMeshElementAllowance=350
VisibleMeshElementWarningRatio=0.8

[DustGame.DustSvcExplosionManager]
mMaxNumActiveExplosions=30
mMaxNumCachedExplosions=30
mCachedExplosionMaxLifeTime=60
mDefaultExplosionLifeTime=3

[DustGame.DustLanguageProfiler]
m_TotalScriptBudget=0.0
m_UScriptBudget=0.0
m_PythonBudget=0.0

[DustGame.DustSvcDebugUtil]
mMaxNumDebugString=20
mDebugStringDrawLocation=(x=300, y=10)
mDebugStringSpace=15
mDebugStringDefaultLifeTime=2

[DustGame.DustCheatManager]
mCreateGameDefaultGameType=gamemode_playineditor
mCreateGameDefaultGameTypeWithGameModeMap=gamemode_skirmish

[UnrealEd.SocketBudgetManager]
SocketMeshBudgets=( Name="Outpost",  Prefix= "OP",  Memory= 999999999, Lod0ModelMemory= 999999999, NumObjects= 999999999)
SocketMeshBudgets=( Name="Landmark", Prefix= "LM_", Memory= 999999999, Lod0ModelMemory= 999999999, NumObjects= 999999999)
MapVariantsToSkip=+AU
MapVariantsToSkip=_TDM
MapVariantsToSkip=_P
MapVariantsToSkip=_CTGuides

[DustGame.DustSvcUIActor]
mSphereRadius=0.f
mSphereRadiusMultiplyer=0.667f
mSphereOffetMultiplyer=3.f
mJoystickFactor=130.f
mUILightingParameters=( R=1, G=1, B=1, X=1, Y=-0.5, Z=0 )
mUILightingParameters=( R=1, G=1, B=1, X=-1, Y=1, Z=0 )
mUILightingParameters=( R=1, G=1, B=1, X=1, Y=0, Z=-1)
mUILightingParameters=( R=1, G=1, B=1, X=1, Y=0, Z=0)

[DustGame.DustAIProfileMgr]
m_aPawnFittingStrings=363955:-1
m_aPawnFittingStrings=351071:-1
m_aPawnFittingStrings=353760:-1
m_aPawnFittingStrings=363935:-1
m_aPawnFittingStrings=364010:-1
m_aPawnFittingStrings=363957:-1
m_aPawnFittingStrings=363934:-1
m_aPawnFittingStrings=353760:352602, 352049, 352049, 352049
m_aPawnFittingStrings=353760:352602, 354914, 354914, 354914
m_aPawnFittingStrings=353767:352602, 352049, 352049
m_aPawnFittingStrings=353767:352602, 354914, 354914
m_aPawnFittingStrings=353769:352602, 352049, 352049, 352049, 352049
m_aPawnFittingStrings=353769:352602, 354914, 354914, 354914, 354914
m_aVehicleFittingStrings=351252:-1
m_aVehicleFittingStrings=351278:351311,351310,351310

[StreamingSocketQuotas]
LargeLodCount=2
LargeBufferDistance=10000.0f
LargeLodDistances=-1
LargeLodDistances=60000.0f
LargeMaxLods=-1
LargeMaxLods=1
LargeMinDistance=70000.0f
LargeMinLod=0
LargeBoundsSize=32768.0f
MediumLodCount=2
MediumBufferDistance=5000.0f
MediumLodDistances=-1
MediumLodDistances=30000.0f
MediumMaxLods=-1
MediumMaxLods=2
MediumMinDistance=35000.0f
MediumMinLod=0
MediumBoundsSize=16384.0f
SmallLodCount=2
SmallBufferDistance=5000.0f
SmallLodDistances=-1
SmallLodDistances=20000.0f
SmallMaxLods=-1
SmallMaxLods=4
SmallMinDistance=25000.0f
SmallMinLod=0
SmallBoundsSize=8192.0f

[IniVersion]
0=0.000000
1=0.000000
2=0.000000
3=0.000000

